# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63cb4ae00ab5d6a829bfa2dc97ce7819b397b40ca53b191b339d49a8c9b65ad3377a9ee8541ad572282c32ecea0ab7379c070563c0db53c036c8d6954d8eab5a

test:
  secret_key_base: 2585827dd0fbd551212b87de5fa20a15109797030b974ab7026159a7d69618b276b82f7db7c122f62ab22544e0df72d71d1d70a5a2863fe69dc5c5126c355ee7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
